/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "AtomicSwapIntegration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AtomicSwapIntegration__factory>;
    getContractFactory(
      name: "OneInchWrapper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OneInchWrapper__factory>;
    getContractFactory(
      name: "StarknetEscrowDst",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StarknetEscrowDst__factory>;
    getContractFactory(
      name: "StarknetEscrowFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StarknetEscrowFactory__factory>;
    getContractFactory(
      name: "StarknetEscrowSrc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StarknetEscrowSrc__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "AtomicSwapIntegration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AtomicSwapIntegration>;
    getContractAt(
      name: "OneInchWrapper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OneInchWrapper>;
    getContractAt(
      name: "StarknetEscrowDst",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StarknetEscrowDst>;
    getContractAt(
      name: "StarknetEscrowFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StarknetEscrowFactory>;
    getContractAt(
      name: "StarknetEscrowSrc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StarknetEscrowSrc>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
